bindings module
Cidan/BetterBags pull request #566
Opened 2024-08-11 11:36 UTC by zeptognome

added bindings module
renamed bound index to isBound (from C_Item)
added bindType number index
added bound boolean index
added bindings keyswords for nonbinding, boe, bou, and quest on all platforms
added bindings keywords for wue, warbound, soulbound for retail

tested on cata and retail

2024-08-13 05:01 UTC, Cidan requested changes
Overall looks good. See minor changes below.

2024-08-13 05:01 UTC, Cidan commented on data/search.lua
> +  search:addStringToIndex(self.indicies.binding, item.bindingInfo.binding, item.slotkey)
because you will want to move this to an enum, you'll probably also want a map of enum -> string values in constants.lua and index those strings.

2024-08-13 06:56 UTC, zeptognome reviewed
enum created as BindingScope as to distinguish from the similar bindType

2024-08-14 00:56 UTC, Cidan reviewed
LGTM, will test tonight and verify behavior.

2024-08-14 01:28 UTC, Cidan approved these changes

2024-08-14 01:28 UTC, merged