Deposit reagents
Cidan/BetterBags pull request #574
Opened 2024-08-12 21:21 UTC by Dabbel

In bank with reagent tab selected, right click deposit normal reagents rather than warbank items

2024-08-12 22:04 UTC, Cidan requested changes

2024-08-12 22:04 UTC, Cidan commented on themes/themes.lua
> +        if BankFrame.selectedTab == 2 then
Please use `bag.bankTab == const.BANK_TAB.REAGENT` here

2024-08-12 22:04 UTC, Cidan commented on themes/themes.lua
> +        if BankFrame.selectedTab == 2 then
See above comment.

2024-08-14 01:29 UTC, Cidan approved these changes
LGTM

2024-08-14 01:30 UTC, merged

2024-09-21 00:31 UTC, burntorangejedi commented
I guess what I'm saying is that I'd like to be able to set preferences per category. 

Example 1 - I'm Mining/Herbalism. When I click the "deposit to warbank" button, everything should go to Warbank (current functionality)

Example 2 - I'm Herbalism/Alchemy. When I click the "deposit to warbank" button, everything goes to warbank EXCEPT all my herbs. Those go, instead, to my Reagent bank so I can access them from the crafting tables and the auction house.

Make sense? Is that possible to do today in some form?

2024-09-21 01:53 UTC, AMaribo commented
> I guess what I'm saying is that I'd like to be able to set preferences per category.
> 
> Example 1 - I'm Mining/Herbalism. When I click the "deposit to warbank" button, everything should go to Warbank (current functionality)
> 
> Example 2 - I'm Herbalism/Alchemy. When I click the "deposit to warbank" button, everything goes to warbank EXCEPT all my herbs. Those go, instead, to my Reagent bank so I can access them from the crafting tables and the auction house.
> 
> Make sense? Is that possible to do today in some form?

Deposit functionality is tied to whatever Blizzard decides should be deposited when clicking the button.